name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, test and documents
      run: |
        npm ci
        npm run build --if-present
        npm test
        npm run doc
    - name: GitHub Pages Deploy
    - uses: EdricChan03/action-build-deploy-ghpages@v2.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Note: You don't have to create this secret - GitHub already does that for you (This input does not have a default value - you have to supply this yourself)
        gh_pages_token: ${{ secrets.ACCESS_TOKEN }} # Note: You have to create this yourself - see the "Secrets used" section above for more info (This input does not have a default value - you have to supply this yourself)
        gh_pages_branch: 'gh-pages' # The GitHub Pages branch to deploy the site to
        gh_pages_dist_folder: 'documentation' # The folder to build the site to
        gh_pages_commit_message: 'Deploy commit $GITHUB_SHA\n\nAutodeployed using $GITHUB_ACTION in $GITHUB_WORKFLOW' # The commit message to use when deploying the site
        remote_repo: 'https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git' # The repository to deploy the site to
        committer_username: '$GITHUB_ACTOR' # The username to use for the committer of the commit
        committer_email: '${GITHUB_ACTOR}@users.noreply.github.com' # The email to use for the committer of the commit
        git_force: ${{ true }} # Whether to use the --force flag when pushing the commit
        override_gh_pages_branch: ${{ false }} # Whether to override the gh-pages branch on push